### ISSUE TITLE
Tag 1.0.3

### ISSUE THREAD

**Issue by djjudas21** [jonmosco/puppet-logwatch#7]
The codebase has moved on a lot since `1.0.2` was tagged. Please could you consider making a new release? Thanks

**Comment by jonmosco** [comment]
Release on the way.  Going to bump module to 2.0 because of the amount of changes and work done.  Also, look for a new release soon to adopt all the Puppet 4.x changes!

**Comment by djjudas21** [comment]
Any sign of 2.0 yet? :smile:

**Comment by jonmosco** [comment]
Pushed.  Thanks!
